fix(template/helm): Add checksum/config annotation (#480)
Add the dynamic `checksum/config` annotation back in.

Previously, this annotation only appeared when `.Values.podAnnotations` was set.

It was only discovered broken by adding podAnnotations and seeing that the `include` context was invalid, leading to this error:

```
Error: template: trino-operator/templates/deployment.yaml:20:28: executing "trino-operator/templates/deployment.yaml" at <include (print $.Template.BasePath "/configmap.yaml") .>: error calling include: template: trino-operator/templates/configmap.yaml:4:10: executing "trino-operator/templates/configmap.yaml" at <.Files.Glob>: nil pointer evaluating interface {}.Glob
```

Note, this was always broken since inception in #7.